-- Additional tables for CineScope Supabase Integration
-- Run this migration after the base schema

-- Favorites table
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  media_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, media_id, media_type)
);

-- Watchlist table
create table if not exists watchlist (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  media_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, media_id, media_type)
);

-- Ratings table
create table if not exists ratings (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  media_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  rating numeric(3,1) not null check (rating >= 0.5 and rating <= 10.0),
  title text not null,
  poster_path text,
  rated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, media_id, media_type)
);

-- User lists (separate from TMDB lists)
create table if not exists user_lists (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- List items
create table if not exists list_items (
  id bigint generated by default as identity primary key,
  list_id bigint references user_lists(id) on delete cascade,
  media_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(list_id, media_id, media_type)
);

-- RSS Feeds (migrated from localStorage)
create table if not exists rss_feeds (
  id uuid default gen_random_uuid() primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  name text not null,
  url text not null,
  description text,
  category text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, url)
);

-- Tracked TV Shows table (for episode tracker)
create table if not exists tracked_shows (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  show_id integer not null,
  name text not null,
  poster_path text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, show_id)
);

-- Watched Episodes table (for episode tracker)
create table if not exists watched_episodes (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  show_id integer not null,
  season_number integer not null,
  episode_number integer not null,
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, show_id, season_number, episode_number)
);

-- Indexes for performance
create index if not exists idx_favorites_user on favorites(user_id);
create index if not exists idx_watchlist_user on watchlist(user_id);
create index if not exists idx_ratings_user on ratings(user_id);
create index if not exists idx_user_lists_user on user_lists(user_id);
create index if not exists idx_list_items_list on list_items(list_id);
create index if not exists idx_rss_feeds_user on rss_feeds(user_id);
create index if not exists idx_tracked_shows_user on tracked_shows(user_id);
create index if not exists idx_watched_episodes_user on watched_episodes(user_id);
create index if not exists idx_watched_episodes_show on watched_episodes(show_id);
