-- Migration: Add TV Episode Tracker Tables
-- Description: Creates tracked_shows and watched_episodes tables for the TV tracker feature
-- Date: 2026-01-02

-- Tracked TV Shows table
-- Stores metadata about shows the user is tracking
create table if not exists tracked_shows (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  show_id integer not null,
  name text not null,
  poster_path text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, show_id)
);

-- Watched Episodes table
-- Stores individual episodes marked as watched
create table if not exists watched_episodes (
  id bigint generated by default as identity primary key,
  user_id integer references profiles(tmdb_id) on delete cascade,
  show_id integer not null,
  season_number integer not null,
  episode_number integer not null,
  watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, show_id, season_number, episode_number)
);

-- Performance indexes
create index if not exists idx_tracked_shows_user on tracked_shows(user_id);
create index if not exists idx_tracked_shows_show on tracked_shows(show_id);
create index if not exists idx_watched_episodes_user on watched_episodes(user_id);
create index if not exists idx_watched_episodes_show on watched_episodes(show_id);
create index if not exists idx_watched_episodes_user_show on watched_episodes(user_id, show_id);

-- Enable Row Level Security
alter table tracked_shows enable row level security;
alter table watched_episodes enable row level security;

-- RLS Policies for tracked_shows
-- Note: These may already exist from supabase-rls-security.sql
-- Using CREATE POLICY IF NOT EXISTS pattern via DO block
do $$
begin
  -- Policy for viewing own tracked shows
  if not exists (
    select 1 from pg_policies
    where tablename = 'tracked_shows'
    and policyname = 'Users can view own tracked shows'
  ) then
    create policy "Users can view own tracked shows"
      on tracked_shows for select
      using (
        exists (
          select 1 from profiles
          where profiles.tmdb_id = tracked_shows.user_id
          and profiles.auth_user_id = auth.uid()
        )
      );
  end if;

  -- Policy for managing own tracked shows
  if not exists (
    select 1 from pg_policies
    where tablename = 'tracked_shows'
    and policyname = 'Users can manage own tracked shows'
  ) then
    create policy "Users can manage own tracked shows"
      on tracked_shows for all
      using (
        exists (
          select 1 from profiles
          where profiles.tmdb_id = tracked_shows.user_id
          and profiles.auth_user_id = auth.uid()
        )
      );
  end if;

  -- Policy for viewing own watched episodes
  if not exists (
    select 1 from pg_policies
    where tablename = 'watched_episodes'
    and policyname = 'Users can view own watched episodes'
  ) then
    create policy "Users can view own watched episodes"
      on watched_episodes for select
      using (
        exists (
          select 1 from profiles
          where profiles.tmdb_id = watched_episodes.user_id
          and profiles.auth_user_id = auth.uid()
        )
      );
  end if;

  -- Policy for managing own watched episodes
  if not exists (
    select 1 from pg_policies
    where tablename = 'watched_episodes'
    and policyname = 'Users can manage own watched episodes'
  ) then
    create policy "Users can manage own watched episodes"
      on watched_episodes for all
      using (
        exists (
          select 1 from profiles
          where profiles.tmdb_id = watched_episodes.user_id
          and profiles.auth_user_id = auth.uid()
        )
      );
  end if;
end $$;
